// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgbrTB9CucWjtpIzq_XonxxOKx_3Wvl8w',
    appId: '1:765550968118:web:9e4006a8270ddb2a198797',
    messagingSenderId: '765550968118',
    projectId: 'xyz-chocolates',
    authDomain: 'xyz-chocolates.firebaseapp.com',
    databaseURL: 'https://xyz-chocolates-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'xyz-chocolates.appspot.com',
    measurementId: 'G-8FCLL15S7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG9LqVMFKk1f4HpjycngiJZQKGL9NleUc',
    appId: '1:765550968118:android:a458fc251fac9609198797',
    messagingSenderId: '765550968118',
    projectId: 'xyz-chocolates',
    databaseURL: 'https://xyz-chocolates-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'xyz-chocolates.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA59WEpAmRv4zQiXbnh9va6opD1OOpgPeo',
    appId: '1:765550968118:ios:d4c3b1d23bc127ec198797',
    messagingSenderId: '765550968118',
    projectId: 'xyz-chocolates',
    databaseURL: 'https://xyz-chocolates-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'xyz-chocolates.appspot.com',
    iosClientId: '765550968118-7v52h2l16bsvd25hoapg1e795k7tc537.apps.googleusercontent.com',
    iosBundleId: 'com.example.xyzChocolates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA59WEpAmRv4zQiXbnh9va6opD1OOpgPeo',
    appId: '1:765550968118:ios:d4c3b1d23bc127ec198797',
    messagingSenderId: '765550968118',
    projectId: 'xyz-chocolates',
    databaseURL: 'https://xyz-chocolates-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'xyz-chocolates.appspot.com',
    iosClientId: '765550968118-7v52h2l16bsvd25hoapg1e795k7tc537.apps.googleusercontent.com',
    iosBundleId: 'com.example.xyzChocolates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgbrTB9CucWjtpIzq_XonxxOKx_3Wvl8w',
    appId: '1:765550968118:web:ff452c7a51a15992198797',
    messagingSenderId: '765550968118',
    projectId: 'xyz-chocolates',
    authDomain: 'xyz-chocolates.firebaseapp.com',
    databaseURL: 'https://xyz-chocolates-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'xyz-chocolates.appspot.com',
    measurementId: 'G-J539P6R2N1',
  );
}
